import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const external = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	...builtinModules,
];

/** @type {import('esbuild').BuildOptions} */
const buildOptions = {
	banner: { js: banner },
	entryPoints: {
		main: "src2/main.ts",
		styles: "src2/styles.css",
	},
	bundle: true,
	external,
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: ".",
	minify: prod,
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
	alias: {
		"react": "preact/compat",
		"react-dom": "preact/compat",
		"react/jsx-runtime": "preact/jsx-runtime",
	},
	jsx: "automatic",
	jsxImportSource: "preact",
	loader: {
		".css": "css",
	},
};

const context = await esbuild.context(buildOptions);

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
