packages:
    - 'packages/*'
    - 'configs/*'

catalog:
    vitest: ^4.0.16
    '@vitest/coverage-v8': ^4.0.16
    typescript: ^5.9.3
    '@types/node': ^22.0.0
    better-sqlite3: ^11.7.0
    '@types/better-sqlite3': ^7.6.12
    eslint: ^9.39.2
    tsx: ^4.21.0
    js-yaml: ^4.1.1
    '@types/js-yaml': ^4.0.9
    yaml: ^2.8.2
