import esbuild from 'esbuild'
import { copyFileSync } from 'node:fs'
import { builtinModules } from 'node:module'
import process from 'process'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

const external = [
	'obsidian',
	'electron',
	'@codemirror/autocomplete',
	'@codemirror/collab',
	'@codemirror/commands',
	'@codemirror/language',
	'@codemirror/lint',
	'@codemirror/search',
	'@codemirror/state',
	'@codemirror/view',
	'@lezer/common',
	'@lezer/highlight',
	'@lezer/lr',
	...builtinModules,
]

/** @type {import('esbuild').BuildOptions} */
const baseOptions = {
	banner: { js: banner },
	bundle: true,
	external,
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outdir: '../..',
	minify: prod,
	define: {
		'process.env.NODE_ENV': prod ? '"production"' : '"development"',
	},
	alias: {
		react: 'preact/compat',
		'react-dom': 'preact/compat',
		'react/jsx-runtime': 'preact/jsx-runtime',
	},
	jsx: 'automatic',
	jsxImportSource: 'preact',
}

/** @type {import('esbuild').BuildOptions} */
const scriptOptions = {
	...baseOptions,
	entryPoints: {
		main: 'src/main.ts',
	},
	loader: {
		'.css': 'empty',
	},
}

/** @type {import('esbuild').BuildOptions} */
const styleOptions = {
	...baseOptions,
	entryPoints: {
		styles: 'src/styles.css',
	},
	loader: {
		'.css': 'css',
	},
}

const scriptContext = await esbuild.context(scriptOptions)
const styleContext = await esbuild.context(styleOptions)

// Copy manifest.json to root for Obsidian/BRAT compatibility
copyFileSync('manifest.json', '../../manifest.json')

if (prod) {
	await Promise.all([scriptContext.rebuild(), styleContext.rebuild()])
	process.exit(0)
} else {
	await scriptContext.watch()
	await styleContext.watch()
}
